name:                hmatrix
version:             0.1.0.0
github:              "maugier/hmatrix"
license:             BSD-3-Clause
author:              "Maxime Augier"
maintainer:          "max@xolus.net"
copyright:           "(C) 2023 Maxime Augier"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maugier/hmatrix#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 1
- text >= 2.0 && < 3
- mtl >= 2.2 && < 3
- ncurses >= 0.2 && < 0.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hmatrix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix

tests:
  hmatrix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix
